### ISSUE TITLE
can't tell the difference between gzdoom and firefox

### ISSUE THREAD

**Issue by Sh4d0wS14d3** [Phate6660/gzdoom-discordrpc#2] opened 2020-09-12 05:46 UTC
Engine: GZDoom
Game: [3.3!] FINAL DOOMER +
Level: ZDoom ◦ View Topic

(I haven't gotten it to work properly with GZDoom itself, so this caught me off-guard at how incorrectly it did the thing. Yay, scripting.)

**Comment by Phate6660** [comment] 2020-09-25 14:04
Yeah, this is a known problem. Because it searches window titles for "project brutality", then "doom" if it can't find it.
I need to work on adding exclusions, the problem is that I just don't have the time right now.
For now, best workaround is just closing your browser.

And I'm very sorry for replying late. Things have been very crazy IRL, and I honestly haven't had much time to be on here.
Please don't take this wrong. When I have the time, trust me, there's a lot of stuff that I'm going to be improving in this project that I've noticed.

**Comment by Phate6660** [comment] 2020-09-27 18:30
I believe I have managed to add exclusions now for Firefox and Pale Moon. I've only tested it a little bit though, so it'd be nice if you tried it and let me know that it worked. @Sh4d0wS14d3

**Comment by Phate6660** [comment] 2021-01-15 05:18
It works for me, and nobody has said anything otherwise so... I'll close this for now.

Anyone can feel free to re-open this later if it's still an issue.

**Closed as completed by Phate6660** 2021-01-15 05:18 UTC
